# Generated by Django 4.2.6 on 2023-12-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Makale'ye video Ekle"),
        ),
    ]
